# Generated by Django 2.2.9 on 2020-05-15 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_officer', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Gender', max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport', models.TextField(blank=True, null=True)),
                ('passport_img', models.ImageField(blank=True, null=True, upload_to='passport')),
                ('right_thumb', models.TextField(blank=True, null=True)),
                ('right_index', models.TextField(blank=True, null=True)),
                ('left_thumb', models.TextField(blank=True, null=True)),
                ('left_index', models.TextField(blank=True, null=True)),
                ('right_thumb_img', models.ImageField(blank=True, null=True, upload_to='right_thumb')),
                ('right_index_img', models.ImageField(blank=True, null=True, upload_to='right_index')),
                ('left_thumb_img', models.ImageField(blank=True, null=True, upload_to='left_thumb')),
                ('left_index_img', models.ImageField(blank=True, null=True, upload_to='left_index')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
