# Generated by Django 2.1.5 on 2020-05-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date_of_entry',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
